### ISSUE TITLE
cannot found MiniMod.WPFTreeViewModel package on nuget

### ISSUE THREAD

**Issue by ricklxm** [mkoertgen/hello.elastic.facetedSearch.wpf#4]
![image](https://user-images.githubusercontent.com/4877955/41350162-c3e61200-6f44-11e8-845d-496299176f4a.png)
https://www.nuget.org/packages?q=MiniMod.WPFTreeViewModel

**Comment by mkoertgen** [comment]
The MiniMod was a checked in class. Removed it as a nuget dependency, so it builds fine now.

Note however, that the example is based on a pretty much outdated elasticsearch version 2.4.4
